name: brian2-binder
channels:
  - brian-team
  - conda-forge
dependencies:
  - python=2.7
  - pip=9.0*
  - cython=0.27*
  - nose=1.3*
  - matplotlib=2.1*
  - brian2
  - brian2tools
  - ipywidgets=7.4.0